# Site settings
url: http://www.arminsadeghi.com
title: Armin Sadeghi
name: Armin Sadeghi
description: Eyes of an Engineer
github: [metadata]
google-analytics: UA-8026452-1

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
excerpt_separator: <!--more-->
timezone: UTC
plugins:
  - jekyll-feed
