# Site settings
url: http://www.arminsadeghi.com
title: Armin Sadeghi
name: Armin Sadeghi
description: Eyes of an Engineer
github: [metadata]
google_analytics: G-116G218LY5

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
excerpt_separator: <!--more-->
timezone: UTC
plugins:
  - jekyll-feed
